#!/bin/bash

read -p "Digite o ip do vps: " ip
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

echo Configurando...
sleep 1
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -A OUTPUT -p tcp -d $ip --dport 443 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp -d $ip --dport 80 -m state --state NEW -j ACCEPT

iptables -A OUTPUT -p tcp --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT

iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables #iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
iptables #iptables -A INPUT -p tcp --dport 8799 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8080 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables #iptables -A OUTPUT -p tcp --dport 3128 -j ACCEPT
iptables #iptables -A OUTPUT -p tcp --dport 8799 -j ACCEPT
iptables -A FORWARD -p tcp --dport 8080 -j ACCEPT
iptables -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables #iptables -A FORWARD -p tcp --dport 3128 -j ACCEPT
iptables #iptables -A FORWARD -p tcp --dport 8799 -j ACCEPT

iptables ##  Allows SSH connections (only 3 attempts by an IP every minute, drop the rest to prevent SSH attacks)
iptables -A INPUT -p tcp -m tcp --dport 22 -m state --state NEW -m recent --set --name DEFAULT --rsource
iptables -A INPUT -p tcp -m tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 3 --name DEFAULT --rsource -j DROP
iptables -A INPUT -p tcp -m state --state NEW --dport 22 -j ACCEPT

iptables # desativa a resposta do comando ping
iptables # descomentar se for usar alterar a porta conforme sua VPS
iptables # use o "ifconfig" para ver sua rede o tipo de dispositivo usado "eth0","eth1","vnet0",etc...
iptables #-A OUTPUT -p icmp -o venet0 -j ACCEPT
iptables #-A INPUT -p icmp --icmp-type echo-request -s 0/0 -i venet0 -j ACCEPT
iptables #-A INPUT -p icmp --icmp-type destination-unreachable -s 0/0 -i venet0 -j ACCEPT
iptables #-A INPUT -p icmp --icmp-type time-exceeded -s 0/0 -i venet0 -j ACCEPT
iptables #-I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables #-A INPUT -p icmp -i venet0 -j DROP
iptables -A INPUT -p icmp --icmp-type echo-request -j DROP

iptables # bloqueia os ataques de flood mais comuns
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

iptables # Libera a porta para usar o Webmin
iptables -A INPUT -p tcp --dport 10000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 10000 -j ACCEPT

iptables # Libera a porta para usar o usermin
iptables -A INPUT -p tcp --dport 20000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 20000 -j ACCEPT

iptables # rejeita peer to peer torrets
iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" -j DROP
iptables -A FORWARD -m string --algo bm --string "peer_id=" -j DROP
iptables -A FORWARD -m string --algo bm --string ".torrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" -j DROP
iptables -A FORWARD -m string --algo bm --string "torrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "announce" -j DROP
iptables -A FORWARD -m string --algo bm --string "info_hash" -j DROP 
iptables -A FORWARD -m string --string "get_peers" --algo bm -j DROP
iptables -A FORWARD -m string --string "announce_peer" --algo bm -j DROP
iptables -A FORWARD -m string --string "find:_node" --algo bm -j DROP

echo -e "\033[1;36mFirewall moficicado
Portas 443 22 8799 8080 80 3128
Bloqueio ICMP
Bloqueio Peer to Peer Torrents
Bloqueio Flood
Pequena proteçao DDoS

CASO QUEIRA TIRAR ESSAS REGRAS IPTABLES EXECUTE A FERRAMENTA ResetFirewall\033[0m"
